id: env_014X6rL6VBM19A3Pmm5fuVQD
name: workshop-pptx
config:
  type: cloud
  networking:
    type: unrestricted
  packages:
    apt:
      - libreoffice
      - poppler-utils
    pip:
      - python-pptx
      # - matplotlib